### ISSUE TITLE
how to configure the file extensions that this extension applied on

### ISSUE THREAD

**Issue by parmentelat** [notebookPowerTools/vscode-jupytext#20]
vscode-jupytext will trigger on a large number of file extensions - 27 as per `src/languages.ts`

It would be nice to have a way to configure this set of file extensions, primarily to avoid the real estate taken up by the *Open as a  Jupyter Notebook* message

**Comment by parmentelat** [comment]
PS
I find it perplexing that the `supportedFileExtensions` variable exported in `src/languages.ts` does not seem to be used anywhere in the code...

**Comment by parmentelat** [comment]
on closer inspection, it seems more like the actual list comes from `resourceLangIds` as hard-coded in `src/commands.ts`

**Comment by DonJayamanne** [comment]
What other file extensions do you want to use this against?

**Comment by parmentelat** [comment]
it's more about using it with fewer languages than with more
in my case I have 0 notebooks saved as a .ts - among others - but still I have this extension enabled on .ts files, I'd like to have a means to disable that

btw. 
I'm currently filing PRs against congyiwu's fork because that is the version that I use on daily basis
is there a good reason for having 2 flavours - I mean, are the changes in that fork not relevant to you ? - and if so would you care to elaborate ?

**Comment by DonJayamanne** [comment]
> is there a good reason for having 2 flavours - I mean, are the changes in that fork not relevant to you 

This extension is no longer actively maintained due to a number of reasons (its hacky and doesn't work very well, i.e. there are a number of scenarios where things do not work well, hence i do not wish to continue with a hacky extension)
The plan is for me to some how (some day) bring this functionality into vscode-jupyter itself.

Please upvote https://github.com/microsoft/vscode-jupyter/issues/1237
